### ISSUE TITLE
2. Prepare dataset.pt file时运行错误

### ISSUE THREAD

**Issue by John-Lin98** [zeaver/MultiFactor#1]
报错信息：
[Data Info] Reading file: ./dataset/cqg/test.json
  0%|                                                                                                                                                                        | 0/7405 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/MultiFactor/multi_factor_dataset.py", line 615, in <module>
    main()
  File "src/MultiFactor/multi_factor_dataset.py", line 597, in main
    dataset = MyDataset(data_path, split, args.data_format, tokenizer)
  File "src/MultiFactor/multi_factor_dataset.py", line 198, in __init__
    p_phrase=sample['p_phrase'],
KeyError: 'p_phrase'

请问作者什么时候上传这些数据和数据集预处理程序（${ProjHome}\preprocess）呢？

我想复现一下本文实现的MultiFactor方法，包括它完整的数据处理、训练和推理的过程，请问作者可以发布本论文的完整代码吗？麻烦作者啦

**Comment by zeaver** [comment]
同学你好：

非常感谢你对这个工作的关注。这份代码之前是论文审稿/Rebuttal期间提交的，还没有处理其中的一些小bug。关于你的疑问：
- 数据处理：这部分代码很麻烦，但是近期我会直接更新处理过后的数据在 ModelScope 或者 HuggingFace 上。预处理代码整理+发布尽量在两周后完成。直接拿数据就能跑训练了。
- 代码完整度：因为代码从公司服务器上下载出来需要脱敏，由于时间紧迫，可能有一些路径错误，代码是完整的。rebuttal期间的实验我是在学校服务器上完成的，代码就是这份 github 上的代码，主要是做了一些路径上的修改。
- 推理：推理我没有写单独的脚本，每个epoch训练之后我都会进行一次evaluation，输出在 `experiments_prefix/.../expoch_x/evaluation_{$split}.json` 文件中. 主要衡量指标是 BLEU4.  本代码仓库 `[evaluate.py](https://github.com/zeaver/MultiFactor/blob/main/evaluate.py)`  文件的作用是测BLEU4、ROUGE、METEOR、BERTScore所有指标。输入是‘evaluation_{$split}.json’，输出是指标结果。

因为我目前要准备 Thesis，我尽量在下周一（2023/11/27）左右完成本仓库的更新，包括 1）数据上传，2）代码bug修复。预处理的代码可能需要两周。

后续有任何疑问，欢迎邮箱联系：zehuaxia@smail.nju.edu.cn

祝好。

**Comment by John-Lin98** [comment]
好的，非常感谢！后续有疑问我用邮箱跟您联系
