### ISSUE TITLE
loading problem

### ISSUE THREAD

**Issue by zwz4949** [zeaver/MultiFactor#2]
![image](https://github.com/zeaver/MultiFactor/assets/73349528/8967d1fa-6f94-4831-8e2c-9093028a6a1a)
I want to load the t5-base model from my local path and I have downloaded all the files about t5-base, but it give me an error like
![image](https://github.com/zeaver/MultiFactor/assets/73349528/7de70320-b9a8-4652-a107-8d89d99e8122)
How could I solve this problem? Thanks!

**Comment by zeaver** [comment]
Thank you for your interest in this work. 
- If using local ckpt, I recommend using absolute paths. 
- According to the way you write it, this is downloading the weight from the remote huggingface, such as `facebook/bart-large`, or directly `t5-base`. `models/t5-base` does not exist in the huggingface repo.

Hope this can solve your problem.

**Comment by zwz4949** [comment]
> Thank you for your interest in this work.
> 
> * If using local ckpt, I recommend using absolute paths.
> * According to the way you write it, this is downloading the weight from the remote huggingface, such as `facebook/bart-large`, or directly `t5-base`. `models/t5-base` does not exist in the huggingface repo.
> 
> Hope this can solve your problem.

ok, thanks! And I have another question. 
![image](https://github.com/zeaver/MultiFactor/assets/73349528/9ee061d5-f332-4711-8212-bf25a5cb1ec3)
![image](https://github.com/zeaver/MultiFactor/assets/73349528/080e34ce-cd34-435c-8de9-891ff09afd25)
I would like to try removing the edge represented by the blue box in the red-bordered area of the model figure. In other words, I would like to know where in the code this particular equation is implemented. Could you help me with that?

**Comment by zeaver** [comment]
I guess you wanna implement the ablation study of `Cls+Gen`? Just set the `model_type` as `node_cls`. You can read the [\[demonstration step6\]](https://github.com/zeaver/MultiFactor/tree/main?tab=readme-ov-file#-53-demostration) for more details. I listed the commands to run the almost all experiments mentioned in my paper at there.

The config setting source code is in https://github.com/zeaver/MultiFactor/blob/main/src/MultiFactor/multi_factor_config.py#L49. when the `if_cross_enhanced_k ` is `False`, there is no $K^{\delta}$ Linear layer in the model's architecture. 

```python
elif re.match(r"node\S*cls", self.model_type, re.I):
    self.model_type = "NodeCls"
    self.if_node_cls = True
    self.if_cross_enhanced_k = False
```

In `src/MultiFactor/modeling_bridget5.py: class T5Attention init`:

```python
self.if_cross_enhanced_k = False
if is_cross and hasattr(config, "if_cross_enhanced_k"):
    if config.if_cross_enhanced_k is True:
        self.if_cross_enhanced_k = True
        self.enhanced_k = nn.Linear(2, self.inner_dim, bias=False)
```

**Comment by zwz4949** [comment]
> I guess you wanna implement the ablation study of `Cls+Gen`? Just set the `model_type` as `node_cls`. You can read the [[demonstration step6]](https://github.com/zeaver/MultiFactor/tree/main?tab=readme-ov-file#-53-demostration) for more details. I listed the commands to run the almost all experiments mentioned in my paper at there.
> 
> The config setting source code is in https://github.com/zeaver/MultiFactor/blob/main/src/MultiFactor/multi_factor_config.py#L49. when the `if_cross_enhanced_k ` is `False`, there is no Kδ Linear layer in the model's architecture.
> 
> ```python
> elif re.match(r"node\S*cls", self.model_type, re.I):
>     self.model_type = "NodeCls"
>     self.if_node_cls = True
>     self.if_cross_enhanced_k = False
> ```
> 
> In `src/MultiFactor/modeling_bridget5.py: class T5Attention init`:
> 
> ```python
> self.if_cross_enhanced_k = False
> if is_cross and hasattr(config, "if_cross_enhanced_k"):
>     if config.if_cross_enhanced_k is True:
>         self.if_cross_enhanced_k = True
>         self.enhanced_k = nn.Linear(2, self.inner_dim, bias=False)
> ```


Thank you for your response. Allow me to further clarify my question. What I mean is that I want to experiment with including only HW^k in the Decoder, without including δW^δ. In other words, I don't want to integrate p(δ|x) into K, but rather, only have K^h=HW^k but not K^h=δW^δ + HW^k. In summary, I would like to test what kind of results we can achieve by using only SpaCy for candidate phrase selection, without performing any subsequent phrase selection. I'm wondering if you can understand my intention and if my idea aligns with your ablation experiment with Cls+Gen? Thanks!
