### ISSUE TITLE
BLUE score

### ISSUE THREAD

**Issue by wangfangfangcn** [zeaver/MultiFactor#3]
Thank you very much for your work. I tried to reproduce your paper according to the steps. After evaluating my results, the RougeL and Meteor indicators are similar to those in the paper, but my BLEU can only reach 19.6, which is far from enough. 21.75 in the paper, I would like to ask if this has happened to you? Or do you think there are any details that I didn't notice?

**Comment by zeaver** [comment]
Thank you very much for your interest in this work. I guess you run this code on the SQuAD Zhou Split with MixQG-base. I recommend trying the operations/checks as follows:
- Evaluate your result with [sacreBLEU](https://github.com/mjpost/sacrebleu) again. In my previous tests, this result fluctuated very little.
- Test the zero-shot performance of MixQG. 19.6 is comparable with fine-tuned MixQG-base.

These experiments were conducted in many random seeds {0, 1, 2, 3, 42}. Small fluctuations is normal, but if the experimental conclusions is conflicted, please feel free to contact me with email. I'd like to solve your problems via QQ/WeChat/Tencent Metting/ or anything that is convenient for you to have a meeting/conversation.

**Comment by wangfangfangcn** [comment]
> Thank you very much for your interest in this work. I guess you run this code on the SQuAD Zhou Split with MixQG-base. I recommend trying the operations/checks as follows:
> 
> * Evaluate your result with [sacreBLEU](https://github.com/mjpost/sacrebleu) again. In my previous tests, this result fluctuated very little.
> * Test the zero-shot performance of MixQG. 19.6 is comparable with fine-tuned MixQG-base.
> 
> These experiments were conducted in many random seeds {0, 1, 2, 3, 42}. Small fluctuations is normal, but if the experimental conclusions is conflicted, please feel free to contact me with email. I'd like to solve your problems via QQ/WeChat/Tencent Metting/ or anything that is convenient for you to have a meeting/conversation.

Thank you very much for your reply. I'm very sorry that I read the wrong value. The BLEU value shown in the paper is 21.24. I used the T5-base model to run the code on the SQuAD Zhou Split. I also used sacreBLEU for evaluation, but I don’t know why my test results have always been lower than 20.

**Comment by zeaver** [comment]
What's your transformers version? Please use the version i wrote in the `requirement.txt`. And it's MultiFactor or only T5-base? You can evaluate the fine-tuned T5-base instead of MultiFactor(T5-base) firstly. Because of the limited information, maybe i could not answer your question exactly.
