### ISSUE TITLE
Scores issue

### ISSUE THREAD

**Issue by xiguaguaaaaa** [zeaver/MultiFactor#4]
Thank you very much for your work. I tried to reproduce your paper according to the steps. After evaluating my results, my BLEU can only reach 19.0, which is far from enough 26.66 in the paper ( MultiFactor (T5-base) Full Document Context ). And the other scores are also very different. I would like to ask if this has happened to you? Or do you think there are any details that I didn't notice?
I have set the 'data_format' to 'multi_factor', and the 'data_name' to 'pcqg', with everything else left as default. I'm not sure if my settings are incorrect.

**Comment by zeaver** [comment]
Thanks for your attention to our this work.

What is the version of transformers? 

And what's the performance of fine-tuned T5-base? This vanilla BLEU-4 baseline is about 25 on supporting-facts setting, and 20.5 on full document setting. It is consistent to the performance shown in [QA4QG](https://arxiv.org/abs/2202.06538), where the BLEU4 socres are 25.69(supporting-facts, BART-base) and 19.69(full-doc, BART-large).

Key hyper-params of training are lr and epoch, which are shown in Table9 in our paper.

If you cannot re-implement this vanilla T5 baseline or have any other questions, please connect me with my email for futher solution via wechat or qq.
