### ISSUE TITLE
关于评估得分

### ISSUE THREAD

**Issue by xiguaguaaaaa** [zeaver/MultiFactor#5]
作者你好，我跑了你的代码后进行评估，但是BLEU分数只能达到19.0，与论文中的26.66（MultiFactor (T5-base) Full Document Context）有些差距，而且其他分数也差很多。
        我的设置是：'data_format'='multi_factor'，'data_name'='pcqg'，其他默认设置。
我想问一下是不是有什么细节我没有注意到？或者是我的设置有误？

**Comment by zeaver** [comment]
Thanks for your attention to our this work.

What is the version of transformers? 

And what's the performance of fine-tuned T5-base? This vanilla BLEU-4 baseline is about 25 on supporting-facts setting, and 20.5 on full document setting. It is consistent to the performance shown in [QA4QG](https://arxiv.org/abs/2202.06538), where the BLEU4 socres are 25.69(supporting-facts, BART-base) and 19.69(full-doc, BART-large).

Key hyper-params of training are lr and epoch, which are shown in Table9 in our paper.

If you cannot re-implement this vanilla T5 baseline or have any other questions, please connect me with my email for futher solution via wechat or qq.

**Comment by xiguaguaaaaa** [comment]
> 感谢您对我们这项工作的关注。
> 
> 变形金刚是什么版本？
> 
> 那么经过微调的T5底座性能如何呢？此普通 BLEU-4 基线在支持事实设置上约为 25，在完整文档设置上约为 20.5。它与[QA4QG](https://arxiv.org/abs/2202.06538)中显示的性能一致，其中 BLEU4 socres 为 25.69（支持事实，BART-base）和 19.69（完整文档，BART-large）。
> 
> 训练的关键超参数是 lr 和 epoch，如我们论文中的表 9 所示。
> 
> 如果您无法重新实现这个普通的T5基线或有任何其他问题，请通过微信或QQ与我联系以获取进一步的解决方案。

transformers版本是4.20.1，lr忘记设置为5e-5了，到时候再跑一边试试。然后MultiFactor w. T5-base中的t5-base是需要先微调的吗？上面那个结果我是直接将parser设置以下设置后直接跑的，data_format='multi_factor'是指MultiFactor w. T5-base吗？我期望跑的实验是MultiFactor w. T5-base的。
```
parser.add_argument('-j', '--job', type=str, default='pcqg', help='choice the dataset')
parser.add_argument('-f', '--data_format', type=str, default='multi_factor', help='choice the data format')
```

**Comment by xiguaguaaaaa** [comment]
```
2024-04-08 05:25:20,889 INFO : test: metric(bleu4=0.17827413700135064, rouge_l=0.36395962414072647, meteor=0.4453888951940278)
```
我更改了lr为1e-4后，结果如上，还是和论文中的table 2 (Full Document Context) 中的结果差的比较远，我是不是还遗漏了什么细节呢：
```
MultiFactor (T5-base): bleu4=26.66, meteor=29.66, rouge_l=43.37
```

**Comment by zeaver** [comment]
同学你好：

我很难根据现有情况直接回答具体的实验设置问题。

可以复现一下 T5-base 或者 MixQG-base 的 baseline 实验（输入：answer + context， 输出：gold question），他们的 BLEU4 分数大概是 25（supporting-facts），19.5（full-doc）。论文 QA4QG 中显示大概也是这个水平。

如果baseline 没问题，但是其他实验还有问题，欢迎进一步探讨。方便的话邮箱联系我，可以通过 qq 或者 微信，甚至腾讯会议等任何你方便的方式解决你的疑问。

非常感谢你对本工作的关注～

**Comment by zwz4949** [comment]
> 同学你好：
> 
> 我很难根据现有情况直接回答具体的实验设置问题。
> 
> 可以复现一下 T5-base 或者 MixQG-base 的 baseline 实验（输入：answer + context， 输出：gold question），他们的 BLEU4 分数大概是 25（supporting-facts），19.5（full-doc）。论文 QA4QG 中显示大概也是这个水平。
> 
> 如果baseline 没问题，但是其他实验还有问题，欢迎进一步探讨。方便的话邮箱联系我，可以通过 qq 或者 微信，甚至腾讯会议等任何你方便的方式解决你的疑问。
> 
> 非常感谢你对本工作的关注～

好的，我后续通过邮箱与你沟通，谢谢！
