### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by imaodong** [zeaver/MultiFactor#6]
您好，在您处理的数据集中，p_phrase和n_phrase字段分别表示什么含义呢？

**Comment by zeaver** [comment]
您好：

数据进行预处理时，对于给定的上下文 $C$ 和人工标注的问句 $Q$，利用抽取工具，例如 spaCy，Stanford Toolkit 对 $C$ 和 $Q$ 进行短语抽取，得到 $P_c$ 和 $P_q$，那么有：
p_phrase = $P_c$ $\cap$ $P_q$,
n_phrase = $P_c$ $-$ p_phrase

动机（个人观点）：
对于给定的输入文本，从文本颗粒度看，从大到小有：句子，短语，词元（token）。从知识增强的文本生成任务看[1]：
- 句子：从句子级别做 content planning 方法与摘要类似，主要是两种：抽取式[2,3] 和生成式。对于抽取式，在 HotpotQA 数据集中不是很适用，因为给定的 supporting fact sentence 可能只有半句话与目标 QA 对有关，将其作为 Q_model 输入，信息密度没有生成式高，例如 MultiFactor 中的 full answer。并且利用 BM25 等 token overlap 的方法对 $C$ 进行句子挑选，选错的概率很高（作者对 SQuAD QG 数据集进行过简单人工评估）。
- 短语：对于目前 factoid QG，基于一个强假设：标注数据中的 p_phrase 一定是和 QA 有关的，而 n_phrase 与目标 QA对 无关。为什么是强假设呢？这涉及到文本表述的多样性问题，即 $Q$ 中 没有出现的短语可能是与 QA对 相关的。这也是 MultiFactor 中使用 soft 概率作为 PET 输入比 one-hot PET 好的一个动机（作者先做的 soft 实验，再做的 one-hot 消融实验），且 PET 的基本操作单元是 token 而非短语，这与 decoder 的操作单元一致。
- token：LLM的基本操作单元，见的不多。以前的 Copy 机制可能算。

最后，非常感谢您对本工作的关注！
如还有问题，欢迎进一步交流。

---

参考：
[1] Yu, Wenhao, et al. [“A Survey of Knowledge-Enhanced Text Generation.”](https://arxiv.org/abs/2010.04389) Jan. 2022.
[2] Zhou, Qingyu, et al. ["Neural Question Generation from Text: A Preliminary Study"](https://arxiv.org/abs/1704.01792). EMNLP, 2017.
[3] Du, Xinya, et al. [“Learning to Ask: Neural Question Generation for Reading Comprehension.”](https://aclanthology.org/P17-1123/) ACL, 2017.

**Comment by imaodong** [comment]
> 您好：
> 
> 数据进行预处理时，对于给定的上下文 C 和人工标注的问句 Q，利用抽取工具，例如 spaCy，Stanford Toolkit 对 C 和 Q 进行短语抽取，得到 Pc 和 Pq，那么有： p_phrase = Pc ∩ Pq, n_phrase = Pc − p_phrase
> 
> 动机（个人观点）： 对于给定的输入文本，从文本颗粒度看，从大到小有：句子，短语，词元（token）。从知识增强的文本生成任务看[1]：
> 
> * 句子：从句子级别做 content planning 方法与摘要类似，主要是两种：抽取式[2,3] 和生成式。对于抽取式，在 HotpotQA 数据集中不是很适用，因为给定的 supporting fact sentence 可能只有半句话与目标 QA 对有关，将其作为 Q_model 输入，信息密度没有生成式高，例如 MultiFactor 中的 full answer。并且利用 BM25 等 token overlap 的方法对 C 进行句子挑选，选错的概率很高（作者对 SQuAD QG 数据集进行过简单人工评估）。
> * 短语：对于目前 factoid QG，基于一个强假设：标注数据中的 p_phrase 一定是和 QA 有关的，而 n_phrase 与目标 QA对 无关。为什么是强假设呢？这涉及到文本表述的多样性问题，即 Q 中 没有出现的短语可能是与 QA对 相关的。这也是 MultiFactor 中使用 soft 概率作为 PET 输入比 one-hot PET 好的一个动机（作者先做的 soft 实验，再做的 one-hot 消融实验），且 PET 的基本操作单元是 token 而非短语，这与 decoder 的操作单元一致。
> * token：LLM的基本操作单元，见的不多。以前的 Copy 机制可能算。
> 
> 最后，非常感谢您对本工作的关注！ 如还有问题，欢迎进一步交流。
> 
> 参考： [1] Yu, Wenhao, et al. [“A Survey of Knowledge-Enhanced Text Generation.”](https://arxiv.org/abs/2010.04389) Jan. 2022. [2] Zhou, Qingyu, et al. ["Neural Question Generation from Text: A Preliminary Study"](https://arxiv.org/abs/1704.01792). EMNLP, 2017. [3] Du, Xinya, et al. [“Learning to Ask: Neural Question Generation for Reading Comprehension.”](https://aclanthology.org/P17-1123/) ACL, 2017.

非常感谢您在百忙之中的回复，受益匪浅！对于您数据的处理我还有一个疑问：test的时候，既然问题Q是不可知的，但是在test dataset中却是有p_phrase和n_phrase，这相当于假设已经知道了关于问题Q的一些信息。本文的任务定义是给定Context和Answer来生成Question，那么为何在test中用到了还未知道的Question呢？期待您的回复！

**Comment by zeaver** [comment]
在进行推理时，还是需要知道上下文有哪些phrase的，并不会利用已知人工标志问题的信息。phrase classification head 直接做inference，并不需要gold question的label做训练。

**Comment by imaodong** [comment]
> 在进行推理时，还是需要知道上下文有哪些phrase的，并不会利用已知人工标志问题的信息。phrase classification head 直接做inference，并不需要gold question的label做训练。

我已明白，感谢您的回复，祝您生活愉快！
